CREATE TABLE bonds (
    isin CHAR(12) PRIMARY KEY,
    bond_name TEXT NOT NULL,
    brand_name TEXT NOT NULL,
    logo_url TEXT,
    website TEXT,
    description TEXT,
    min_investment NUMERIC(15, 2) NOT NULL,
    min_units INTEGER NOT NULL,
    max_units INTEGER NOT NULL,
    yield_pct NUMERIC(6, 2) NOT NULL,
    coupon_rate NUMERIC(6, 2) NOT NULL,
    coupon_type VARCHAR(50) NOT NULL,
    payout_frequency VARCHAR(50),
    face_value NUMERIC(15, 2) NOT NULL,
    nature VARCHAR(100) NOT NULL,
    seniority VARCHAR(100) NOT NULL,
    mode_of_issue VARCHAR(100) NOT NULL,
    yield_type VARCHAR(50) NOT NULL,
    security_cover NUMERIC(8, 2),
    debenture_trustee TEXT,
    date_of_issue DATE NOT NULL,
    maturity_date DATE NOT NULL,
    rating VARCHAR(20),
    rating_agency VARCHAR(50),
    rating_date DATE,
    total_interest NUMERIC(15, 2) NOT NULL,
    total_principal NUMERIC(15, 2) NOT NULL,
    total_payout NUMERIC(15, 2) NOT NULL,
    interest_frequency VARCHAR(50),
    principal_frequency VARCHAR(50),
    remaining_tenure_months INTEGER NOT NULL,
    risk_bucket VARCHAR(30) NOT NULL,
    sector VARCHAR(100) NOT NULL,
    yield_bucket VARCHAR(30) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CHECK (yield_pct >= 0),
    CHECK (coupon_rate >= 0),
    CHECK (max_units >= min_units),
    CHECK (maturity_date > date_of_issue)
);